### ISSUE TITLE
Stuck M-button

### ISSUE THREAD

**Issue by Ederborg** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#37]
Hello and thank you for doing all of this I really like this firmware and I hope newer versions with more functions will be released soon!

The problem I found is that I somehow got the M-button to be stuck. I think it happened when i hold the M-button down and then cycled thru the menu with the power button, or some combination of power and M-button. After I rebooted everything it goes in to DFU-mode (because of the stuck M-button). When this happened I uploaded the same version of firmware thru BT but the problem is still there and the screen never turned on again.

I don't think it's the hardware because I took it apart again and tinkered with the button and circuit board and the problem was still there. 

But, then i soldered on the wires again and flashed it with the ST-Link. After that everything was back to normal.
At first I was 100% sure that it was a hardware problem, but flashing it again should not solve that!? :)

**Comment by geeksville** [comment]
hmm. that does sound strange.  I think it must have been hardware and during your soldering something got jiggled and the button unstuck.

I say this because I know we have no persistent sw state for monitoring buttons.  And we always just read a GPIO directly.  So for now I'm going to close this bug (just to keep github tidy).  Please reopen if needed.  Thanks!

**Comment by Ederborg** [comment]
I understand :) I will try to reproduce this later (Im on vaccation right now) and maybe film it. Because the whole screen also started to run slow and show some graphical errors, then it stopped bootin correctly. I hope it was a hardware fault.

Thanks again for doing all of this!
