### ISSUE TITLE
Organize repository structure

### ISSUE THREAD

**Issue by lowPerformer** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#8]
Hello everyone,

I think we should reorganize the repo structure. Everything about the SW102 is scattered accross different projects:
- Wiki in the Color_LCD
- some code in SW102_LCD_Bluetooth  AND SW102_LCD_Bluetooth-bootloader

Why not making one project 'SW102 LCD'
with
src -> firmware
src -> bootloader
releases
wiki -> files for wiki
...

**Comment by casainho** [comment]
For me seems a good idea.

**Comment by geeksville** [comment]
I think we actually might want to merge with the Color LCD tree.  Because I'm super eager (after the initial sw102 release) to merge much of the two codebases.  As I've been adding the applayer goo for the sw102 I've been trying to do it in a way so we can eventually (with very little work have something like this)

src/firmware/common - shared code between 850C and SW102 (the screen.c stuff, the config menu stuff, the button handling stuff, preferences saving and loading, packet parsing and composition). 

src/firmware/850C - the particular screen layout definitions for that unit, the uart, flash and device specific code.  top level makefile

src/firmware/sw102 - same as above but for the sw102. toplevel makefile also cool bluetooth features

This would allow future bugfixes and enhancements to mostly be shared between the two 'next gen' devices.

re: bootloader location
I have no opinion on that, but whatever ya'll prefer sounds great to me.

**Comment by geeksville** [comment]
btw: if you want to make this change sooner rather than later, do you want me to submit my PR now?  it certainly isn't ready for end users but it is pretty close (and I fear merge hell ;-) )

**Comment by lowPerformer** [comment]
No need to hurry!

Merge SW102 stuff to the Color_LCD tree is fine for me. But maybe we stay in this tree for the very first dev phases until we are ready for the common code base?

**Comment by casainho** [comment]
I think it  is a very good idea!! Please go ahead.

**Comment by geeksville** [comment]
ok - I'll send my current WIP PR now.  Any feedback or changes would be welcomed.

I'll keep working on it and will send a 'feature complete (i.e. does work for all the things a user wants, might have some UI ugliness though)' PR in the next few days.

**Comment by lowPerformer** [comment]
We can discuss this again when code bases merged.
